/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.drgestao.view;

import java.awt.Color;
import java.awt.Window;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import static javax.swing.KeyStroke.getKeyStroke;

/**
 *
 * @author rafa_
 */
public class DialogConfirmacao extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogConfirmacao.class.getName());
    private boolean confirmado = false;

    /**
     * Creates new form DialogConfirmacao
     */
    public DialogConfirmacao(Window dona, String titulo, String detalhe, String valor, String mensagem, String rodape, String textoBotao, boolean perigoso) {
        super(dona, ModalityType.APPLICATION_MODAL);
        initComponents();
 
        lblTitulo.setText(titulo);
        lblDetalhe.setText(detalhe);
        jLabel1.setText(valor);
        lblMenssagem.setText(mensagem);
        jLabel2.setText(rodape);
        btnConfirmar.setText(textoBotao);
 
        pnlDetalhe.setVisible(!detalhe.isEmpty());
 
        if (perigoso) {
            btnConfirmar.setBackground(new Color(155, 44, 44));
        } else {
            btnConfirmar.setBackground(new Color(181, 84, 28));
        }
 
        getRootPane().setDefaultButton(btnCancelar);

        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "fechar");
        getRootPane().getActionMap().put("fechar", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
    }
    
    public static boolean perguntar(Window dona, String titulo, String detalhe, String valor, String mensagem, String rodape, String textoBotao, boolean perigoso){
        DialogConfirmacao d = new DialogConfirmacao(dona, titulo, detalhe, valor, mensagem, rodape, textoBotao, perigoso);
        d.setLocationRelativeTo(dona);
        d.setVisible(true);
        return d.confirmado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlDetalhe = new javax.swing.JPanel();
        lblDetalhe = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMenssagem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmar");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(480, 300));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setText("Excluir este Lançamento ?");

        pnlDetalhe.setBackground(new java.awt.Color(247, 245, 241));
        pnlDetalhe.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 14, 12, 14));
        pnlDetalhe.setLayout(new java.awt.BorderLayout());

        lblDetalhe.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblDetalhe.setText("2 x Chiclete");
        pnlDetalhe.add(lblDetalhe, java.awt.BorderLayout.LINE_START);

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("R$ 2,00");
        pnlDetalhe.add(jLabel1, java.awt.BorderLayout.LINE_END);

        lblMenssagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMenssagem.setText("Comanda nº 128  Mesa 4. O total passa de R$ 58,00 para R$ 56,00");

        jLabel2.setForeground(new java.awt.Color(90, 97, 102));
        jLabel2.setText("A exclusão fica registrada no log com o operador");

        btnConfirmar.setBackground(new java.awt.Color(155, 44, 44));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Excluir Lançamento");
        btnConfirmar.setPreferredSize(new java.awt.Dimension(190, 44));
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(30, 35, 38));
        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(110, 44));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlDetalhe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMenssagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDetalhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMenssagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        confirmado = true;
        dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDetalhe;
    private javax.swing.JLabel lblMenssagem;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlDetalhe;
    // End of variables declaration//GEN-END:variables
}
